Update image tests
atbcb/ICTTestingBaseline pull request #421
Opened 2023-07-18 14:55 UTC by kengdoj

2023-07-19 20:03 UTC, cliffbert commented on _baselines/06Images.md
> +-   The image tests evaluate the images as they were coded to indicate whether they are meaningful or decorative, leaving that determination to the author of the content. There are certain scenarios
"The image tests _attempt to_ evaluate the images as they were coded ... _However_, there are scenarios where ..."?

2023-07-19 20:04 UTC, cliffbert commented on _baselines/06Images.md
> +-   All images must be evaluated. . Some images will have multiple tests.
Some images will _require/fall under/?_ multiple tests

2023-07-19 20:12 UTC, cliffbert commented on _baselines/06Images.md
>      <ol>
Check that none of the following are true?

2023-07-19 20:16 UTC, cliffbert commented on _baselines/06Images.md
> +-   An image that has a non-empty accessible name has been determined to be meaningful by the content author. The author has decided that this image should not be ignored by assistive technology.
Note: while redundant accessible text is not marked as a failure in this test, the tester may still wish to advise the author to avoid such in the future.

2023-07-19 20:17 UTC, cliffbert reviewed
Nicely done ... just some minor suggestions

2023-07-20 18:02 UTC, kengdoj commented on _baselines/06Images.md
> +-   All images must be evaluated. . Some images will have multiple tests.
How about

```suggestion
-   All images must be evaluated. Multiple tests may apply to an image. 
```

2023-07-20 18:03 UTC, kengdoj commented on _baselines/06Images.md
> +-   An image that has a non-empty accessible name has been determined to be meaningful by the content author. The author has decided that this image should not be ignored by assistive technology.
I think that note could go in a test process.

2023-07-20 18:04 UTC, kengdoj commented on _baselines/06Images.md
> +    <li id="1TI-6">Check that the non-empty text alternative (combination of accessible name and accessible description) provides an equivalent description of the image. </li>
the "refers" would be part of the text alternative already if it was done programmatically.

2023-07-20 18:05 UTC, kengdoj commented on _baselines/06Images.md
>      <ol>
I like that.

2023-07-20 18:08 UTC, kengdoj commented on _baselines/06Images.md
> +<li id="2TI-2">Check that the image is not any of the following [SC 1.1.1]:
```suggestion
<li id="2TI-2">Check that none of the following are true [SC 1.1.1]:
```

2023-07-20 18:09 UTC, kengdoj commented on _baselines/06Images.md
> +    <li id="1TI-2">Check that the image is not any of the following [SC 1.1.1]:
```suggestion
    <li id="1TI-2">Check that none of the following are true [SC 1.1.1]:
```

2023-07-20 18:12 UTC, kengdoj commented on _baselines/06Images.md
> +-   The image tests evaluate the images as they were coded to indicate whether they are meaningful or decorative, leaving that determination to the author of the content. There are certain scenarios
there is no attempt. there is only do.

2023-07-27 13:20 UTC, cliffbert commented on _baselines/06Images.md
> +-   The image tests evaluate the images as they were coded to indicate whether they are meaningful or decorative, leaving that determination to the author of the content. There are certain scenarios
I know what you mean, but the next sentence contradicts the first - leaving the determination to the authors vs our deciding that their determination is incorrect, so it seems that some wriggle room is needed. e.g. "The image tests first take the image markup (i.e., whether meaningful or decorative) at face value to allow for the author's intent. However, ..."

2023-07-27 13:24 UTC, cliffbert commented on _baselines/06Images.md
> +    <li id="1TI-6">Check that the non-empty text alternative (combination of accessible name and accessible description) provides an equivalent description of the image. </li>
Ah yes

2023-07-27 13:50 UTC, KMSOC commented on _baselines/06Images.md
> +<li id="2TI-2">Check that there are no non-empty text alternative attributes. The presence of such attributes may cause assistive technology to not ignore the image. [SC 1.1.1]
Are these the only two ways currently to add text alternative attributes? If so, perhaps call that out more explicitly instead of just in an example (where someone will need to surmise we are talking about title and alt)?

2023-07-27 23:03 UTC, kengdoj commented on _baselines/06Images.md
> +-   The image tests evaluate the images as they were coded to indicate whether they are meaningful or decorative, leaving that determination to the author of the content. There are certain scenarios
```suggestion
-   The image tests evaluate the images as they were coded to indicate whether they are meaningful or decorative, leaving that determination to the author of the content. However, there are certain scenarios as described in the tests where the author's determination would be incorrect.
```

2023-07-27 23:07 UTC, kengdoj commented on _baselines/06Images.md
> +<li id="2TI-2">Check that there are no non-empty text alternative attributes. The presence of such attributes may cause assistive technology to not ignore the image. [SC 1.1.1]
The intent of these examples is to show that having attributes for BOTH decorative _and_ meaningful would be a failure. The previous test checks for the decorative attributes. This step tests that there are no meaningful attributes.

2023-07-28 13:35 UTC, cliffbert commented on _baselines/06Images.md
> +-   The image tests evaluate the images as they were coded to indicate whether they are meaningful or decorative, leaving that determination to the author of the content. There are certain scenarios
Sure

2023-07-28 18:29 UTC, cliffbert commented on _baselines/ChangeLog3.md
> +| 6. Images | Test Method Rationale: added "The image tests evaluate the images as they were coded to indicate whether they are meaningful or decorative, leaving that determination to the author of t
Need update to line 15

2023-07-31 13:51 UTC, kengdoj commented on _baselines/ChangeLog3.md
> +| 6. Images | Test Method Rationale: added "The image tests evaluate the images as they were coded to indicate whether they are meaningful or decorative, leaving that determination to the author of t
What kind of update?

2023-07-31 13:57 UTC, cliffbert approved these changes

2023-07-31 20:10 UTC, kengdoj commented on _baselines/ChangeLog3.md
> +| 6. Images | Test Method Rationale: added "The image tests evaluate the images as they were coded to indicate whether they are meaningful or decorative, leaving that determination to the author of t
```suggestion
| 6. Images | Test Method Rationale: added "The image tests evaluate the images as they were coded to indicate whether they are meaningful or decorative, leaving that determination to the author of the content. However, there are certain scenarios as described in the tests where the author's determination would be incorrect." |
```

2023-07-31 20:10 UTC, kengdoj commented on _baselines/ChangeLog3.md
> +| 6. Images | Test Method Rationale: added "The image tests evaluate the images as they were coded to indicate whether they are meaningful or decorative, leaving that determination to the author of t
Ah, thanks. Change made.

2023-07-31 20:18 UTC, cliffbert approved these changes

2023-07-31 22:08 UTC, kengdoj commented on _baselines/06Images.md
> +<li id="2TI-2">Check that there are no non-empty text alternative attributes. The presence of such attributes may cause assistive technology to not ignore the image. [SC 1.1.1]
```suggestion
<li id="2TI-2">Check that there are no non-empty text alternative attributes. Numerous attributes contribute to the computation of the accessible name and accessible description. Refer to <a href="https://www.w3.org/TR/html-aam-1.0/#img-element" target="_blank" rel="noopener">HTML Accessibility API Mappings 1.0 for img</a>. The presence of such attributes may cause assistive technology to not ignore the image. [SC 1.1.1]
```

2023-07-31 22:09 UTC, kengdoj commented on _baselines/06Images.md
> +<li id="2TI-2">Check that there are no non-empty text alternative attributes. The presence of such attributes may cause assistive technology to not ignore the image. [SC 1.1.1]
@KMSOC - Is above suggested change any better?

2023-08-08 20:48 UTC, kengdoj commented on _baselines/06Images.md
> +<li id="2TI-2">Check that there are no non-empty text alternative attributes. The presence of such attributes may cause assistive technology to not ignore the image. [SC 1.1.1]
@KMSOC - do you have further changes or is this resolved?

2023-08-09 11:58 UTC, KMSOC commented on _baselines/06Images.md
> +<li id="2TI-2">Check that there are no non-empty text alternative attributes. The presence of such attributes may cause assistive technology to not ignore the image. [SC 1.1.1]
resolved!

2023-08-16 14:57 UTC, KMSOC commented on _baselines/06Images.md
> +<li id="2TI-2">Check that there are no non-empty text alternative attributes. The presence of such attributes may cause assistive technology to not ignore the image. [SC 1.1.1]
All good!

2023-08-22 15:08 UTC, drewnielson commented on _baselines/06Images.md
> +-   The image tests evaluate the images as they were coded to indicate whether they are meaningful or decorative, leaving that determination to the author of the content. However, there are certain s
```suggestion
-   The image tests evaluate the images as coded to indicate whether they are meaningful or decorative, leaving that determination to the author of the content. However, there are certain scenarios, as described in the tests, where the author's programmatic determination could be incorrect.
```

2023-08-22 15:16 UTC, drewnielson commented on _baselines/06Images.md
> +-   An image that has an empty accessible name has been determined to be decorative by the content author. The author has decided that this image should be ignored by assistive technology.
```suggestion
-   An image that has an empty accessible name has been determined to be decorative by the content author. The author has determined that this image should be ignored by assistive technology.
```

2023-08-22 15:19 UTC, drewnielson commented on _baselines/06Images.md
> +### 6.1 Test Procedure for Images with non-empty text alternative
```suggestion
### 6.1 Test Procedure for Images with a non-empty text alternative
```

2023-08-22 15:20 UTC, drewnielson commented on _baselines/06Images.md
> +        <li id="1TI-2i">Image is page design/formatting and could be ignored by assistive technology without any loss of meaning.</li>
```suggestion
        <li id="1TI-2i">The image is page design/formatting and could be ignored by assistive technology without any loss of meaning.</li>
```

2023-08-22 15:20 UTC, drewnielson commented on _baselines/06Images.md
> +        <li id="1TI-2ii">Image is not visible on the page.</li>
```suggestion
        <li id="1TI-2ii">The image is not visible on the page.</li>
```

2023-08-22 15:24 UTC, drewnielson commented on _baselines/06Images.md
> +### 6.2 Test Procedure for Images with empty text alternative
```suggestion
### 6.2 Test Procedure for Images with an empty text alternative
```

2023-08-22 15:28 UTC, drewnielson commented on _baselines/06Images.md
> +<p id="2IC">Identify any image (i.e., <code>img</code> element, or element with <code>role=”img”</code>, or CSS background image) that has an empty text alternative. </p>
```suggestion
<p id="2IC">Identify any image (i.e., <code>img</code> element, or element with <code>role=”img”</code>, or element that includes a CSS background image) that has an empty text alternative. </p>
```

2023-08-22 15:32 UTC, drewnielson commented on _baselines/06Images.md
> +<li id="2TI-2">Check that none of the following are true [SC 1.1.1]:
```suggestion
<li id="2TI-2">Check that none of the following is true [SC 1.1.1]:
```

2023-08-22 15:33 UTC, drewnielson commented on _baselines/06Images.md
> +        <li id="2TI-2a">Image is the only way to convey meaningful information.</li>
```suggestion
        <li id="2TI-2a">The image is the only way to convey meaningful information.</li>
```

2023-08-22 15:33 UTC, drewnielson commented on _baselines/06Images.md
> +        <li id="2TI-2b">Image is in the tab order.</li>
```suggestion
        <li id="2TI-2b">The image is in the tab order.</li>
```

2023-08-22 15:34 UTC, drewnielson commented on _baselines/06Images.md
> +        <li id="2TI-2c">Image is a functional image that initiates action.</li>
```suggestion
        <li id="2TI-2c">The image is a functional image that initiates action.</li>
```

2023-08-22 15:37 UTC, drewnielson submitted a review, later dismissed
Added suggested minor wording changes

2023-08-22 16:06 UTC, michaelhortongsa approved these changes
Reviewed. No changes.

2023-08-22 18:31 UTC, bletalien requested changes
Just a few minor things for consideration.

2023-08-22 18:31 UTC, bletalien commented on _baselines/06Images.md
> +-   The image tests evaluate the images as coded to indicate whether they are meaningful or decorative, leaving that determination to the author of the content. However, there are certain scenarios,
```suggestion
-   The image tests evaluate the images as coded to discern whether the author of the content has determined they are meaningful or decorative. However, there are certain scenarios, as described in the tests, where the author's programmatic determination could be incorrect.
```
I'm not sure if I hadn't been privy to the conversations whether I'd be able to parse the first sentence. The first part, until the comma, seems to say that evaluating the images as coding will tell you whether the images are meaningful or decorative, which, of course, is backwards.

2023-08-22 18:31 UTC, bletalien commented on _baselines/06Images.md
>  -   Commonly used image formats include .jpg, .png, .svg, .gif, .tiff, .bmp. Other graphic formats are also in use and should be considered for this test.
```suggestion
-   Commonly used image formats include .jpg, .png, .svg, .gif, .tiff,  and.bmp. Other graphic formats are also in use and should be considered for this test.
```

2023-08-22 18:31 UTC, bletalien commented on _baselines/06Images.md
>  -   Decoration, Formatting, Invisible: If image is pure decoration, is used only for visual formatting, or is not presented to users, then it is implemented in a way that it can be ignored by assisti
```suggestion
-   Decoration, Formatting, Invisible: If the image is pure decoration, is used only for visual formatting, or is not presented to users, then it is implemented in a way that it can be ignored by assistive technology.
```

2023-08-22 18:31 UTC, bletalien commented on _baselines/06Images.md
>  -   CAPTCHA: If the purpose of the image is to confirm that content is being accessed by a person rather than a computer, then text alternatives that identify and describe the purpose of the image(s)
I don't know why it's not letting me make a proper note about this text, but recommend changing "contains the note: 'Note'" to something that won't distract, either by removing the second "Note" or by changing the first one to "following."

2023-08-22 18:31 UTC, bletalien commented on _baselines/06Images.md
>  -   CAPTCHA: If the purpose of the image is to confirm that content is being accessed by a person rather than a computer, then text alternatives that identify and describe the purpose of the image(s)
Okay, I have decided that displaying the rich diff, which seemed like a good idea, is just confusing me. There are a few places where in the rich diff, it looks like things will go wrong, e.g., spaces will go missing or words will stay that should go away. I'm trusting you'll work it out, and I'm happy to give another read once you've pushed all updates.

2023-08-22 18:31 UTC, bletalien commented on _baselines/06Images.md
>  ### 6.3 Test Procedure for Captchas
"Check that the non-empty text alternative (combination... ) identifies and describes the purpose of the CAPTCHA." The verb needs to agree with "text alternative."

2023-08-22 20:41 UTC, kengdoj commented on _baselines/06Images.md
> +-   Commonly used image formats include .jpg, .png, .svg, .gif, .tiff,  and .bmp. Other graphic formats are also in use and should be considered for this test.
```suggestion
-   Commonly used image formats include .jpg, .png, .svg, .gif, .tiff, and .bmp. Other graphic formats are also in use and should be considered for this test.
```

2023-08-22 20:46 UTC, bletalien commented on _baselines/06Images.md
> +-   Commonly used image formats include .jpg, .png, .svg, .gif, .tiff,  and .bmp. Other graphic formats are also in use and should be considered for this test.
Fair enough. Nice catch

2023-08-22 20:47 UTC, kengdoj commented on _baselines/06Images.md
>  ### 6.3 Test Procedure for Captchas
Thanks, fixed.

2023-08-22 20:48 UTC, kengdoj commented on _baselines/06Images.md
> +-   Commonly used image formats include .jpg, .png, .svg, .gif, .tiff,  and .bmp. Other graphic formats are also in use and should be considered for this test.
haha, it has a mind of its own.

2023-08-22 21:44 UTC, kengdoj commented on _baselines/06Images.md
> +-   An image that has an empty accessible name has been determined to be decorative by the content author. The author has determined that this image should be ignored by assistive technology.
```suggestion
-   An image that has an empty accessible name has been determined to be decorative by the content author. The author has determined that this image should be ignored by assistive technology.

- [Presentational Roles Conflicts](https://www.w3.org/TR/wai-aria-1.1/#conflict_resolution_presentation_none) has inconsistent accessibility support.
    - "If an element with a role of presentation is focusable, or otherwise interactive, user agents MUST ignore the normal effect of the role and expose the element with implicit native semantics, in order to ensure that the element is both [understandable](https://www.w3.org/TR/wai-aria-1.1/#dfn-understandable) and [operable] (https://www.w3.org/TR/wai-aria-1.1/#dfn-operable)." Because accessibility support is inconsistent, this Baseline checks that an image with an empty text alternative is not in the tab order nor a functional image.
    - "User agents MUST always expose [global WAI-ARIA states and properties](https://www.w3.org/TR/wai-aria-1.1/#global_states) to accessibility APIs, even if an element has an explicit or inherited role of presentation. In this case, the user agent ignores the presentation role and exposes the element according to its implicit native semantics." Because accessibility support is inconsistent, this Baseline checks that an image with an empty text alternative does not have a non-empty `aria-labelledby`, `aria-label`, or `aria-describedby` attribute.
```

2023-08-22 22:48 UTC, kengdoj commented on _baselines/06Images.md
> +    <li id="1TI-5">Check that aria-hidden is <strong>NOT</strong> set to "true".[SC 1.3.1]</li>
```suggestion
```

There is no presentational conflict with `aria-hidden="true"` regardless of other text alternative attributes, so I don't think this test is needed. An image with `aria-hidden="true"` will have an empty text alternative and would not be covered by this test.

See my email on 6/30/2023 5:42 PM with subject "Re: images":

> ANDI would not include role=presentation or none in gANDI, but gANDI does include <img aria-hidden=”true”>. gANDI’s ANDI Output for such an image is empty like with alt=””; there’s no error flagged that it has no accessible name. 

ANDI will flag an image link with no accessible name, which is good.

2023-08-22 22:51 UTC, kengdoj commented on _baselines/06Images.md
> +        <li> Fail Example 2: <code>&lt;img alt="turtle" role="presentation"&gt;</code></li>
```suggestion
        <li> Fail Example 2: <code>&lt;img aria-label="turtle" role="presentation"&gt;</code></li>
```

2023-08-28 20:32 UTC, kengdoj commented on _baselines/06Images.md
> +    - "User agents MUST always expose [global WAI-ARIA states and properties](https://www.w3.org/TR/wai-aria-1.1/#global_states) to accessibility APIs, even if an element has an explicit or inherited
```suggestion
    - "User agents MUST always expose [global WAI-ARIA states and properties](https://www.w3.org/TR/wai-aria-1.1/#global_states) to accessibility APIs, even if an element has an explicit or inherited role of presentation. In this case, the user agent ignores the presentation role and exposes the element according to its implicit native semantics." "Authors SHOULD NOT provide meaningful alternative text (for example, use `alt=""` in HTML) when the presentation role is applied to an image." [WAI-ARIA 1.1, presentation (role)](https://www.w3.org/TR/wai-aria-1.1/#presentation). Because accessibility support is inconsistent, this Baseline checks that an image that has `role="presentation"` or `role="none"` does not have a non-empty text alternative attribute, and an image that has a non-empty text alternative does not have `role="presentation"` or `role="none"`.
```

2023-08-28 20:40 UTC, kengdoj commented on _baselines/06Images.md
> +    <li id="1TI-6">Check that the non-empty text alternative (combination of accessible name and accessible description) provides an equivalent description of the image. </li>
```suggestion
    <li id="1TI-6">Check that the non-empty text alternative (combination of accessible name and accessible description) provides an equivalent description of the image's purpose. </li>
```

2023-08-28 20:45 UTC, kengdoj commented on _baselines/06Images.md
> +<li id="2TI-2">Check that there are no non-empty text alternative attributes. The presence of such attributes may cause assistive technology to not ignore the image, i.e., provide the image's text al
```suggestion
<li id="2TI-2">Check that none of the following is true [SC 1.1.1]:
    <ol>
        <li id="2TI-2a">The image is the only way to convey meaningful information.</li>
        <li id="2TI-2b">The image is in the tab order.</li>
        <li id="2TI-2c">The image is a functional image that initiates action.</li>
    </ol>
</li>

<li id="2TI-3">Check that there are no non-empty text alternative attributes. The presence of such attributes may cause assistive technology to not ignore the image, i.e., provide the image's text alternative to the user. [SC 1.1.1]
```

2023-08-28 20:47 UTC, kengdoj commented on _baselines/06Images.md
> +<li id="2TI-2">Check that none of the following is true [SC 1.1.1]:
```suggestion
```

2023-08-28 20:47 UTC, kengdoj commented on _baselines/06Images.md
> +        <li id="2TI-2a">The image is the only way to convey meaningful information.</li>
```suggestion
```

2023-08-28 20:47 UTC, kengdoj commented on _baselines/06Images.md
> +        <li id="2TI-2b">The image is in the tab order.</li>
```suggestion
```

2023-08-28 20:48 UTC, kengdoj commented on _baselines/06Images.md
> +        <li id="2TI-2c">The image is a functional image that initiates action.</li>
```suggestion
```

2023-08-28 20:54 UTC, kengdoj commented on _baselines/06Images.md
> +    <ol>
```suggestion
```

2023-08-28 20:54 UTC, kengdoj commented on _baselines/06Images.md
> +</li>
```suggestion
```

2023-08-28 20:59 UTC, kengdoj commented on _baselines/06Images.md
> +    - "If an element with a role of presentation is focusable, or otherwise interactive, user agents MUST ignore the normal effect of the role and expose the element with implicit native semantics, i
```suggestion
    - "If an element with a role of presentation is focusable, or otherwise interactive, user agents MUST ignore the normal effect of the role and expose the element with implicit native semantics, in order to ensure that the element is both [understandable](https://www.w3.org/TR/wai-aria-1.1/#dfn-understandable) and [operable](https://www.w3.org/TR/wai-aria-1.1/#dfn-operable)." Because accessibility support is inconsistent, this Baseline checks that an image with an empty text alternative is not in the tab order nor a functional image.
```

2023-08-28 21:01 UTC, kengdoj commented on _baselines/06Images.md
> +<p id="1IC">Identify any image (i.e., <code>img</code> element or an element with <code>role="img"</code>) that has a non-empty text alternative (combination of the accessible name and accessible des
```suggestion
<p id="1IC">Identify any image (i.e., <code>img</code> element or an element with <code>role= "img"</code>) that has a non-empty text alternative (combination of the accessible name and accessible description) per the <a href="https://www.w3.org/TR/html-aam-1.0/#img-element">HTML Accessibility API Mappings 1.0 for img</a>. </p>
```

2023-08-28 21:03 UTC, kengdoj commented on _baselines/06Images.md
> +<p id="2IC">Identify any image (i.e., <code>img</code> element, or element with <code>role=”img”</code>, or element that includes a CSS background image) that has an empty text alternative. </p>
```suggestion
<p id="2IC">Identify any image (i.e., <code>img</code> element, or element with <code>role="img"</code>, or element that includes a CSS background image) that has an empty text alternative. </p>
```

2023-08-28 21:05 UTC, kengdoj commented on _baselines/06Images.md
> +<li id="2TI-3">Check that there are no non-empty text alternative attributes. The presence of such attributes may cause assistive technology to not ignore the image, i.e., provide the image's text al
```suggestion
<li id="2TI-3">For images with `role="presentation"` or `role="none"`, check that there are no non-empty text alternative attributes. The presence of such attributes may cause assistive technology to not ignore the image, i.e., provide the image's text alternative to the user. [SC 1.1.1]
```

2023-08-28 21:06 UTC, kengdoj commented on _baselines/06Images.md
> +        <li> Fail Example 1: <code>&lt;img alt="" title="use your notes"&gt;</code></li>
```suggestion
        <li> Fail Example 1: <code>&lt;img role="none" alt="use your notes"&gt;</code></li>
```

2023-08-28 21:11 UTC, kengdoj commented on _baselines/06Images.md
> +<li id="2TI-3">For images with `role="presentation"` or `role="none"`, check that there are no non-empty text alternative attributes. The presence of such attributes may cause assistive technology to
```suggestion
<li id="2TI-3">For images with <code>role="presentation"</code> or <code>role="none"</code>, check that there are no non-empty text alternative attributes. The presence of such attributes may cause assistive technology to not ignore the image, i.e., provide the image's text alternative to the user. [SC 1.1.1]
```

2023-08-28 21:16 UTC, kengdoj commented on _baselines/06Images.md
> +    <li id="1TI-6">Check that the non-empty text alternative (combination of accessible name and accessible description) provides an equivalent description of the image's purpose. </li>
```suggestion
    <li id="1TI-5">Check that the non-empty text alternative (combination of accessible name and accessible description) provides an equivalent description of the image's purpose. [SC 1.1.1]</li>
```

2023-08-28 22:43 UTC, merged