Editorial recommendation for Test Procedure for Audio Description (SC 1.2.5)
atbcb/ICTTestingBaseline pull request #422
Opened 2023-07-21 19:24 UTC by bruce-usab

- add case for media using player without AD functionality
- change "audio" to "narration
- provide link to, and example of, "media alternative for text"

This PR is to facilitate a conversation with baseline folks about assessing if narration **adequately** describes important visual content in the media,

2023-07-26 23:46 UTC, kengdoj commented on _baselines/17SyncMedia.md
> +    <li id="5TI-2">Check that the narration (with audio descriptions enabled) adequately describes important visual content in the media, including information about actions, characters, scene change
Audio includes sounds and speech. Narration is just speech.
 
- Would a train whistle be adequate to describe a train passing?

2023-07-27 23:13 UTC, kengdoj commented on _baselines/17SyncMedia.md
> +    <li id="5TI-1">Enable audio descriptions through multimedia player functions and play the media.  If a separate media file with audio descriptions is provided, test that file.  If there is not a
```suggestion
    <li id="5TI-1">Enable audio descriptions through multimedia player functions (if available) and play the media.  If a separate media file with audio descriptions is provided, test that file. </li>
```

2023-07-27 23:14 UTC, kengdoj requested changes
See my responses/suggestion.

2023-07-28 13:29 UTC, cliffbert commented on _baselines/17SyncMedia.md
> +    <li id="5TI-2">Check that the narration (with audio descriptions enabled) adequately describes important visual content in the media, including information about actions, characters, scene change
Agreed

2023-07-28 13:31 UTC, cliffbert commented on _baselines/17SyncMedia.md
> +    <li id="5TI-1">Enable audio descriptions through multimedia player functions and play the media.  If a separate media file with audio descriptions is provided, test that file.  If there is not a
Agreed

2023-09-21 20:46 UTC, kengdoj requested changes
The PR's suggested change to "narration" is not accepted.

2024-01-02 17:00 UTC, KMSOC commented on _baselines/17SyncMedia.md
> +    <li id="5TI-1">Enable audio descriptions through multimedia player functions and play the media.  If a separate media file with audio descriptions is provided, test that file.  If there is not a
Did you mean to say "medial" file in line 128, or should it be "media" file?

2024-01-02 17:03 UTC, cliffbert commented on _baselines/17SyncMedia.md
> +    <li id="5TI-1">Enable audio descriptions through multimedia player functions and play the media.  If a separate media file with audio descriptions is provided, test that file.  If there is not a
media

2024-01-02 19:03 UTC, kengdoj commented on _baselines/17SyncMedia.md
> +    <li id="5TI-2">Check that the narration (with audio descriptions enabled) adequately describes important visual content in the media, including information about actions, characters, scene change
@cliffbert, what do you agree with?

2024-03-27 21:45 UTC, closed without merging